/**
 * Copyright 2017 Google Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.google.youtube.gaming.chat;

import java.util.Arrays;

import net.minecraftforge.client.ClientCommandHandler;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.Mod.EventHandler;
import net.minecraftforge.fml.common.ModMetadata;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;

/**
 * Main entry point for YouTube Chat. Provides the chat service API to other mods, e.g.
 *
 * YouTubeChatService youTubeChatService = YouTubeChat.getService();
 */
@Mod(modid = StreamChat.MODID, name = StreamChat.NAME, version = StreamChat.VERSION, clientSideOnly = true, guiFactory = StreamChat.GUI_FACTORY)
public class StreamChat
{
    public static final String MODID = "stream_chat";
    public static final String NAME = "Stream Chat";
    public static final String VERSION = "1.3.0-1.12.1";
    public static final String GUI_FACTORY = "com.google.youtube.gaming.chat.ConfigGuiFactory";
    private static StreamChatService service;
    public static final JsonUtil json = new JsonUtil();

    public static synchronized StreamChatService getService()
    {
        if (service == null)
        {
            service = new ChatService();
        }
        return service;
    }

    @EventHandler
    public void preInit(FMLPreInitializationEvent event)
    {
        StreamChat.initModInfo(event.getModMetadata());
        ConfigManager.initialize(event.getSuggestedConfigurationFile());
        ChatService service = (ChatService) StreamChat.getService();
        ClientCommandHandler.instance.registerCommand(new CommandYouTubeChat(service));
        ClientCommandHandler.instance.registerCommand(new CommandChatMock(service));
        ClientCommandHandler.instance.registerCommand(new CommandChatAction(service));
    }

    private static void initModInfo(ModMetadata info)
    {
        info.autogenerated = false;
        info.modId = StreamChat.MODID;
        info.name = StreamChat.NAME;
        info.description = "Enables interaction with Live Stream Chat.";
        info.version = StreamChat.VERSION;
        info.authorList = Arrays.asList("jimrogers");
        info.credits = "Credit to PeregrineZ for implemented Example Features";
    }
}