/**
 * Copyright 2017 Google Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.google.youtube.gaming.chat;

import java.util.Arrays;

import net.minecraftforge.client.ClientCommandHandler;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.Mod.EventHandler;
import net.minecraftforge.fml.common.ModMetadata;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;

/**
 * Main entry point for YouTube Chat. Provides the chat service API to other mods, e.g.
 *
 * YouTubeChatService youTubeChatService = YouTubeChat.getService();
 */
@Mod(modid = YouTubeChat.MODID, name = YouTubeChat.NAME, version = YouTubeChat.VERSION, clientSideOnly = true, guiFactory = YouTubeChat.GUI_FACTORY)
public class YouTubeChat
{
    public static final String MODID = "ytchat";
    public static final String NAME = "YouTube Chat";
    public static final String VERSION = "1.3.0-1.8.9";
    public static final String GUI_FACTORY = "com.google.youtube.gaming.chat.YouTubeConfigurationGuiFactory";
    private static YouTubeChatService service;
    public static final JsonUtil json = new JsonUtil();

    public static synchronized YouTubeChatService getService()
    {
        if (service == null)
        {
            service = new ChatService();
        }
        return service;
    }

    @EventHandler
    public void preInit(FMLPreInitializationEvent event)
    {
        YouTubeChat.initModInfo(event.getModMetadata());
        YouTubeConfiguration.initialize(event.getSuggestedConfigurationFile());
        ChatService service = (ChatService) YouTubeChat.getService();
        ClientCommandHandler.instance.registerCommand(new CommandYouTubeChat(service));
        ClientCommandHandler.instance.registerCommand(new CommandChatMock(service));
        ClientCommandHandler.instance.registerCommand(new CommandChatAction(service));
    }

    private static void initModInfo(ModMetadata info)
    {
        info.autogenerated = false;
        info.modId = YouTubeChat.MODID;
        info.name = YouTubeChat.NAME;
        info.description = "Enables interaction with YouTube Livestream Chat.";
        info.version = YouTubeChat.VERSION;
        info.authorList = Arrays.asList("jimrogers");
        info.credits = "Credit to PeregrineZ for implemented Example Features";
    }
}